### ISSUE TITLE
Uber/ Type Randomizer

### ISSUE THREAD

**Issue by Gerdat14** [Dunstklinge/Stadium_2_Randomizer#1]
So, I'm running the most current version of Project 64, but each time I try to use a rom generated using the Type Randomizer, I get the "In a Permanent loop that cannot be exited. Emulation will now stop. Verify Rom and it's Settings." Error. Nothing I have tried has fixed this, although running the normal version of the rom seems to be working fine.

**Comment by Dunstklinge** [comment]
Can confirm the bug on my end. Seems to happen with all Uber randomisation options. I forgot to make them recalculate the ROMs crc. I'll see if i can fix it this weekend.

Until then, here are your options for a workaround:
1: Tick an option in the randomizer that forces a crc update. Those would be "Seperate Items for seperate rental sets", "Seperate PokkeCup-Rentals" as well as the custom trainer options.. 
2: fix the crc manually. There is a tool out there called "Real N64 Crc Tool v2" that can do that. You have to launch if from a command prompt with the -u option, like rn64crc.exe -u "yourRomName.z64"

**Comment by Dunstklinge** [comment]
New Version is up. Would be great if you can test it out and see if the problem persists or is gone.
If you encounter freezes when viewing the intro or selecting rentals, make sure you read the new things added to the readme. apparently project 64 seems to struggle a bit without these settings.

**Comment by DolanSmirks** [comment]
How do i open the randomizer?

**Comment by Dunstklinge** [comment]
Its a regular windows executable, you just double click the exe file.
Make sure you downloaded the .zip file from the releases page, and not the source code or something else (github has a pretty confusing layout for this kind of stuff)
Releases Page is here if you have trouble finding it:
https://github.com/Dunstklinge/Stadium_2_Randomizer/releases

**Comment by DolanSmirks** [comment]
I know now how to download it but when i randomize the ROM. When i try to open it the randomized ROM crashes.

Hämta Outlook för Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Dunstklinge** [comment]
Have you tried the steps from the [https://github.com/Dunstklinge/Stadium_2_Randomizer/blob/master/README.md]readme(url), i.e switching the emulation method to something more stable? Does it happen with every setting, or only once certain settings are selected? Some Settings modify the roms protected area, which p64 cant handle in recompiler mode.

If that doesnt work, it would be helpful if you could give me the exact settings and emulator version so i can reprodce the crash over here.
